title: Under construction
description: If you're seeing this message, you've caught me in the middle of building out a new version of this site
author: Brian Ramos
url: brian-ramos.com

social-twitter: bramos
social-github: brirams
social-linkedin: brian-ramos-6ba41713
remote_theme: brirams/grayscale-theme

grayscale-theme:
  first-name: Brian
  last-name: Ramos

social:
    - title: twitter
      url: https://twitter.com/bramos
    - title: github
      url: https://github.com/brirams
    - title: linkedin
      url: https://www.linkedin.com/in/brian-ramos-6ba41713/
color:
    primary-dark: '#000000'
    links: '#219ab3'

footer: Brian Ramos

plugins:
  - jekyll-remote-theme
