title: Brian Ramos
description: A simple beachhead of a site. I probably won't post much but maybe I will!
about-author: Well seasoned infrastructure engineer with a penchant for overkill
author: Brian Ramos
author-img: headshot-min.png
url: brian-ramos.com

social-twitter: bramos
social-github: brirams
social-linkedin: brian-ramos-6ba41713
remote_theme: brirams/grayscale-theme

grayscale-theme:
  first-name: Brian
  last-name: Ramos

plugins:
  - jekyll-remote-theme
