title: Brian Ramos
description: Computers and things
author: Brian Ramos
url: brian-ramos.com

remote_theme: brirams/grayscale-theme

social:
    - title: twitter
      url: https://twitter.com/bramos
    - title: github
      url: https://github.com/brirams
    - title: linkedin
      url: https://www.linkedin.com/in/brian-ramos-6ba41713/
color:
    primary-dark: '#000000'
    links: '#219ab3'

footer: Brian Ramos 

plugins:
  - jekyll-remote-theme
